# Generated by Django 4.2.4 on 2023-08-11 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0004_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.BigIntegerField(default=0, editable=False, primary_key=True, serialize=False),
        ),
    ]
