# Generated by Django 4.2.4 on 2023-08-10 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Likes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='like',
            name='created_by',
        ),
        migrations.AddField(
            model_name='like',
            name='user_id',
            field=models.BigIntegerField(blank=True, default=-1),
        ),
    ]
