# Generated by Django 4.2.4 on 2023-08-10 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Likes', '0002_remove_like_created_at_remove_like_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='post_id',
            field=models.BigIntegerField(blank=True, default=-1),
        ),
    ]
