# Generated by Django 4.2.4 on 2023-08-11 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.BigIntegerField(blank=True, default=-1, unique=True)),
                ('created_by_id', models.BigIntegerField(blank=True, default=-1)),
                ('likes_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='LikeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(blank=True, default=-1)),
                ('post_id', models.BigIntegerField(blank=True, default=-1)),
            ],
            options={
                'indexes': [models.Index(fields=['id'], name='Likes_likee_id_679d20_idx')],
            },
        ),
    ]
