# Generated by Django 4.2.4 on 2023-08-11 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0003_delete_user_post_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.BigIntegerField(editable=False, primary_key=True, serialize=False),
        ),
    ]
